apiVersion: v1
kind: Service
metadata:
  name: my-angular-project
spec:
  selector:
    app: my-angular-project
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http 
  type: NodePort
