apiVersion: v1
kind: Service
metadata:
  name: {{ template "my-angular-project.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.externalPort }}
      protocol: TCP
  selector:
    app: {{ template "my-angular-project.name" . }}
    tier: {{ .Values.service.tier }}
